dyte-io/ui-kit

.releaserc.js
WEB-4029
Publish package to `npmjs.com` npm registry
=> feat: enable package publishing

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, packages/angular-library/README.md, packages/core/README.md, packages/react-library/README.md
|  Fixes WEB-4032 |
Added the following documents
1. README
2. CONTRIBUTING
3. CODE_OF_CONDUCT
4. LICENSE
=> chore: added open source documents

packages/core/src/components/dyte-participant-tile/dyte-participant-tile.tsx, packages/core/src/components/dyte-simple-grid/dyte-simple-grid.tsx
=> fix: move pip controls to web-core

packages/core/package.json
=> fix: update web-core version

.github/workflows/deploy.yml
|  Fixes WEB- 4037 |
Deploy script to deploy ui-kit to github actions
=> fix: github actions deploy

.github/workflows/deploy.yml, .github/workflows/pr-comment.yml
|  Fixes WEB-4037 |
Fix CI build step
=> fix: github actions build step

packages/core/package.json
=> chore: bump web core version

packages/core/src/components/dyte-participant-tile/dyte-participant-tile.css
=> fix: update z-index for dyte-avatar

packages/core/src/components/dyte-participant-tile/dyte-participant-tile.css
=> fix: use absolute dimensions for avatar

.github/workflows/deploy.yml, .github/workflows/pr-comment.yml, .github/workflows/release.yml, .releaserc.js, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, package-lock.json, packages/angular-library/README.md, packages/angular-library/projects/components/package.json, packages/core/README.md, packages/core/package.json, packages/core/src/components/dyte-camera-toggle/dyte-camera-toggle.tsx, packages/core/src/components/dyte-grid/dyte-grid.tsx, packages/core/src/components/dyte-mic-toggle/dyte-mic-toggle.tsx, packages/core/src/components/dyte-participant-tile/dyte-participant-tile.css, packages/core/src/components/dyte-participant-tile/dyte-participant-tile.tsx, packages/core/src/components/dyte-permissions-message/dyte-permissions-message.tsx, packages/core/src/components/dyte-screen-share-toggle/dyte-screen-share-toggle.tsx, packages/core/src/components/dyte-settings-video/dyte-settings-video.tsx, packages/core/src/components/dyte-setup-screen/dyte-setup-screen.tsx, packages/core/src/components/dyte-simple-grid/dyte-simple-grid.tsx, packages/core/src/lib/lang/default-language.ts, packages/core/src/utils/sidebar.ts, packages/react-library/README.md, packages/react-library/package.json, packages/vue-library/package.json
=> chore: release

packages/core/src/components/dyte-livestream-player/dyte-livestream-player.css, packages/core/src/components/dyte-livestream-player/dyte-livestream-player.tsx
| fixes WEB-4074 |
Added CF based livestreaming. Removed IVS.
Note: Live-streaming UI is not meant to have PIP toggle. PIP is part of the player for viewers.
=> fix: remove IVS

packages/core/src/components/dyte-chat/dyte-chat.tsx
=> fix: add private chat filter

packages/core/src/components/dyte-chat/dyte-chat.tsx
=> fix: remove socket service flag check

packages/core/src/components/dyte-debugger-audio/dyte-debugger-audio.tsx, packages/core/src/components/dyte-debugger-screenshare/dyte-debugger-screenshare.tsx, packages/core/src/components/dyte-debugger-system/dyte-debugger-system.tsx, packages/core/src/components/dyte-debugger-video/dyte-debugger-video.tsx, packages/core/src/components/dyte-debugger/dyte-debugger.tsx, packages/core/src/lib/lang/default-language.ts, packages/core/src/utils/debugger-utils.ts
| fixes WEB-4073 |
Added internationalisation support for debugger/troubleshooter.
=> fix(debugger-i18n): fixed the lack of i18n in debugger files

.github/workflows/release.yml, packages/core/src/components.d.ts
=> fix: github action for staging update

packages/core/src/components/dyte-chat/dyte-chat.tsx
=> fix: remove socket service check

.github/PULL_REQUEST_TEMPLATE.md, packages/core/src/components/dyte-participants/dyte-participants.tsx, packages/core/src/lib/lang/default-language.ts
| fixes WEB-4084 |
Added missing i18n terms for participants tab
=> fix(participants-tab-i18n): fixed i18n issues in the participants tab

packages/core/src/components/dyte-network-indicator/dyte-network-indicator.tsx
| fixes WEB-4097 |
Showing network indicator for Self as well.
=> fix(network-indicator): show network indicator for self as well

packages/core/src/components/dyte-participant-tile/dyte-participant-tile.tsx
=> fix(tile): add network-indicator part attr

CHANGELOG.md, package-lock.json, packages/angular-library/projects/components/package.json, packages/angular-library/projects/components/src/lib/stencil-generated/components.ts, packages/core/package.json, packages/core/src/components.d.ts, packages/core/src/components/dyte-markdown-view/dyte-markdown-view.tsx, packages/core/src/components/dyte-participants-audio/dyte-participants-audio.tsx, packages/core/src/lib/audio.ts, packages/core/src/lib/builder/index.ts, packages/react-library/package.json, packages/vue-library/package.json, packages/vue-library/src/components.ts
| fixes WEB-4109 |
This release contains the following
1. Chat indentation in dyte-chat
2. ui-kit-addons ordering issue
3. recording audio fixes
=> chore(release): ui-kit-addon ordering, hand raise, code indentation in dyte-chat

packages/core/src/components/dyte-setup-screen/dyte-setup-screen.tsx
=> fix: join in as text

packages/core/src/components/dyte-microphone-selector/dyte-microphone-selector.tsx, packages/core/src/components/dyte-speaker-selector/dyte-speaker-selector.tsx
=> fix: simplify device list logic

packages/core/src/components/dyte-grid/dyte-grid.tsx, packages/core/src/components/dyte-participant-tile/dyte-participant-tile.tsx, packages/core/src/types/dyte-client.ts
=> fix: add source spam on web-core

packages/core/src/components.d.ts, packages/core/src/components/dyte-simple-grid/dyte-simple-grid.tsx
=> fix: error while destructuring meeting

packages/core/src/lib/lang/default-language.ts
=> fix: update mute all description

package-lock.json, packages/core/package.json
=> chore: bump web-core for release testing

packages/core/src/components/dyte-plugin-main/dyte-plugin-main.tsx
=> fix: handle iframe not found exceptions

packages/core/src/components/dyte-text-composer-view/dyte-text-composer-view.tsx
Auto-focuses the textarea when opening chat
=> feat(dyte-text-composer-view): focus textarea when opening chat

packages/core/src/components/dyte-notification/dyte-notification.css
=> fix: truncate notifications after two lines

packages/angular-library/projects/components/package.json
Adds the angular output files to Angular package.json.
=> fix: angular package.json
