dyte-io/ui-kit

packages/core/src/components/dyte-camera-toggle/dyte-camera-toggle.tsx, packages/core/src/components/dyte-mic-toggle/dyte-mic-toggle.tsx
|  fixes WEB-4012  |
When the permission for audio or video is dynamically disabled in a session, the affected participants' video and audio toggle button disappear from the controlbar. They also re-appear when the permission is dynamically provided.
=> fix: toggle controlbar icon on dynamic permission change

packages/core/src/components/dyte-camera-toggle/dyte-camera-toggle.tsx, packages/core/src/components/dyte-mic-toggle/dyte-mic-toggle.tsx, packages/core/src/components/dyte-screen-share-toggle/dyte-screen-share-toggle.tsx
| fixes WEB-4021 |
Mic and camera toggle were shown off stage in cases where permissions were altered midway using dynamic permissions or  ui-kit addons.
As a webinar viewer, Stay off stage and run the following code snippet
```
// Set Not permissions as allowed
Object.defineProperty(
this.meeting?.self.permissions,
"canProduceAudio", {
value: 'NOT_ALLOWED',
configurable: true
}
);
meeting?.self.permissions.emit("micPermissionUpdate");
// Now Set permissions as Allowed
Object.defineProperty(
this.meeting?.self.permissions,
"canProduceAudio", {
value: 'ALLOWED',
configurable: true
}
);
meeting?.self.permissions.emit("micPermissionUpdate");
```
=> fix(off-stage-actions): mic and camera toggle should not be shown off stage

packages/core/src/utils/sidebar.ts
| fixes WEB-4023 |
In case of dynamic permission change, Chat box was getting hidden due to the canViewChat check. Added canReceive similar to the chatPrivate.canReceive.
Note: Web Core equivalent is not added yet. It has to be added and the type casting has to be removed from this PR.
Run the following code snippet for presets that have everything disabled for public chats.
```
Object.defineProperty(
meeting?.self.permissions.chatPublic,
"canReceive",
{
value: true
}
);
```
=> feat(internal): added ability to show view only public chat

packages/core/src/components/dyte-grid/dyte-grid.tsx, packages/core/src/components/dyte-participant-tile/dyte-participant-tile.tsx, packages/core/src/components/dyte-settings-video/dyte-settings-video.tsx, packages/core/src/components/dyte-setup-screen/dyte-setup-screen.tsx
- init pip controller before populating participants. Fixes a race where participant videos were added in pip before init
- use isPreview when rendering self outside dyte-grid
- do not use video with isPreview as source for pip
=> fix: pip misc bugs

.github/workflows/deploy.yml, package-lock.json, packages/core/package.json
|  Fixes WEB-4046 |
`uikit.dyte.app` doesn't use the `staging` build of web-core, this PR changes that in the actions yaml file
=> chore: deploy web-core staging in uikit.dyte.app

packages/core/src/components/dyte-permissions-message/dyte-permissions-message.tsx, packages/core/src/lib/lang/default-language.ts
- Handle multiple permission failures at the same time (ie screenshare system denied, camera denied)
- Show systems settings deep link for macOS SYSTEM_DENIED
- Do not show audio,video permission images steps for Chrome screenshare SYSTEM_DENIED
=> feat: improve macos permission messages

packages/core/src/components/dyte-camera-selector/dyte-camera-selector.tsx, packages/core/src/components/dyte-microphone-selector/dyte-microphone-selector.tsx, packages/core/src/components/dyte-speaker-selector/dyte-speaker-selector.tsx
When you start by not giving permissions in the init call with `{ audio: false, video: false }`, and then when you give permission in the Setup Screen by clicking the mic/camera toggles, the device list didn't get updated.
This PR fixes that.
=> fix: update device selector state as per media permission state

packages/core/src/components/dyte-participants-stage-list/dyte-participants-stage-list.tsx, packages/core/src/components/dyte-participants-viewer-list/dyte-participants-viewer-list.tsx, packages/core/src/components/dyte-participants/dyte-participants.tsx, packages/core/src/components/dyte-virtualized-list/dyte-virtualized-participant-list.tsx, packages/core/src/utils/sidebar.ts
| fixes WEB-4074 |
1. Showing viewers list and Stage list to all viewers. Earlier livestreams didn't used to have viewer tab and viewers didn't have the option to see other viewers or hosts.
2. Made some performance fixes. 
3. Changed Stage tab label to Participants
=> feat(livestream): show livestream viewers and stage list

packages/core/src/components/dyte-ai-transcriptions/dyte-ai-transcriptions.tsx
=> fix: scroll lock in transcriptions

packages/core/src/components.d.ts, packages/core/src/components/dyte-chat/dyte-chat.tsx, packages/core/src/components/dyte-livestream-player/dyte-livestream-player.tsx
| fixes WEB-4088 |
Added CF based livestream viewer with stats
=> feat(internal): CF livestream viewer with stats

packages/core/src/components/dyte-participant/dyte-participant.tsx
| fixes WEB-4094 |
Fixed these:
1. Participant menu item was opening towards bottom rather than top for last few participants. Due to this actions such as pin & kick were not visible.
2. Menu List was not closing if any other participant was clicked.
=> fix(participants): participant menu list was not closing, actions were invisible for last few participants

packages/core/src/components/dyte-markdown-view/dyte-markdown-view.tsx
| fixes WEB-4104 |
Fixed indentation issues with chat messages. Each message with a code block, now can have its own individual scroll for the content.
Only requisite is that the code should be pre-formatted. There will be no language specific formatting performed on messages.
https://github.com/user-attachments/assets/e507beea-c39f-481a-b0d9-84b6bacfa49c
=> fix(dyte-chat): fixed code indentation for chat messages

packages/core/src/lib/builder/index.ts
| fixes WEB-4109 |
There was a peculiar issue where in [ui kit add-ons](https://github.com/dyte-io/ui-kit-addons/blob/main/index.html#L91) if hand raise, if not place last, will not show the hand raise button in control bar, and fail with an error in console logs.
It was happening because config was being cloned on every `register` method call of every addon.
Since all other addons work with the meeting object they have received in register method, they work as expected, even if placed anywhere in the registerAddons list.
However hand raise button gets added using config and gets its properties, as well, such as `meeting` from config . 
If config gets cloned deeply, identity of meeting object gets lost. If identity is lost, WeakMap of web-core CDN build …
=> fix(ui-kit-addons): hand raise addon if not place at the end of the addon list, failed to add hand raise button

packages/core/src/components/dyte-participant-tile/dyte-participant-tile.tsx
| fixes WEB-4133 |
With some changes around media refactoring in web-core, consuming & receiving meeting.meta.mediaStates were renamed to send & recv, which were missed in ui-kit code, causing issues.
Fixing the fields.
=> fix(dyte-participant-tile): network disconnected icon is not going away due to incorrect field

.github/workflows/release.yml, package-lock.json, packages/core/package.json
| fixes WEB-4133 |
Fixed CI/CD release workflow. It was failing because it was picking an old web-core version that wasn't compatible. Using CI to avoid all sorts of caches.
=> ci(release): fixed released, using npm ci instead of install, updated utils to match web-core

packages/core/src/utils/config.ts
| fixes WEB-4143 |
Breakout rooms toggle was not showing up if config was not re-evaluated, even when breakout was enabled and breakout was going on.
Though the proper fix would be to ensure re-evaluation but there could always be faulty useEffects when it comes to react.
Removing the check from config because breakout room toggle button is already doing this check https://github.com/dyte-io/ui-kit/blob/main/packages/core/src/components/dyte-breakout-room-toggle/dyte-breakout-rooms-toggle.tsx#L54 and it won't anyway render itself. Having 2 source of truths could be error prone so marking breakout rooms toggle button as the source of truth.
=> fix(breakout-rooms): breakout room button is missing was cases where config was not re-evaluated

packages/core/src/lib/lang/index.ts
Too many locale objects are created when using `dyte-meeting` or any component where `useLanguage` will be called multiple times. This PR addresses that by making sure `useLanguage` returns the `defaultLanguage` object when needed and not new objects every time.
=> fix: optimize locale object handling

packages/core/src/components/dyte-plugin-main/dyte-plugin-main.tsx
Use arrow function in plugin-main component to avoid stable state issues.
=> fix: use arrow function in plugin-main to avoid state issues

.github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Speed up github actions - since `npm install` takes up 5 minutes which is a major chunk of time taken by the actions.
Also bumped `node-version` to 22 which is the current LTS.
Refer: https://github.com/actions/setup-node?tab=readme-ov-file#caching-global-packages-data
=> chore: bump node to 22 (lts), and cache npm deps

packages/core/src/components/dyte-ai-toggle/dyte-ai-toggle.css, packages/core/src/components/dyte-ai-toggle/dyte-ai-toggle.tsx, packages/core/src/components/dyte-camera-toggle/dyte-camera-toggle.css, packages/core/src/components/dyte-camera-toggle/dyte-camera-toggle.tsx, packages/core/src/components/dyte-chat-toggle/dyte-chat-toggle.css, packages/core/src/components/dyte-chat-toggle/dyte-chat-toggle.tsx, packages/core/src/components/dyte-controlbar-button/dyte-controlbar-button.css, packages/core/src/components/dyte-controlbar/dyte-controlbar.css, packages/core/src/components/dyte-fullscreen-toggle/dyte-fullscreen-toggle.css, packages/core/src/components/dyte-fullscreen-toggle/dyte-fullscreen-toggle.tsx, packages/core/src/components/dyte-livestream-toggle/dyte-livestream-toggle.css, packages/core/src/components/dyte-livestream-toggle/dyte-livestream-toggle.tsx, packages/core/src/components/dyte-mic-toggle/dyte-mic-toggle.css, packages/core/src/components/dyte-mic-toggle/dyte-mic-toggle.tsx, packages/core/src/components/dyte-more-toggle/dyte-more-toggle.css, packages/core/src/components/dyte-participants-toggle/dyte-participants-toggle.css, packages/core/src/components/dyte-participants-toggle/dyte-participants-toggle.tsx, packages/core/src/components/dyte-pip-toggle/dyte-pip-toggle.css, packages/core/src/components/dyte-pip-toggle/dyte-pip-toggle.tsx, packages/core/src/components/dyte-plugins-toggle/dyte-plugins-toggle.css, packages/core/src/components/dyte-plugins-toggle/dyte-plugins-toggle.tsx, packages/core/src/components/dyte-polls-toggle/dyte-polls-toggle.css, packages/core/src/components/dyte-polls-toggle/dyte-polls-toggle.tsx, packages/core/src/components/dyte-screen-share-toggle/dyte-screen-share-toggle.css, packages/core/src/components/dyte-screen-share-toggle/dyte-screen-share-toggle.tsx, packages/core/src/components/dyte-stage-toggle/dyte-stage-toggle.css, packages/core/src/components/dyte-stage-toggle/dyte-stage-toggle.tsx, packages/core/src/lib/default-ui-config.ts, packages/core/src/utils/config.ts
Keyboard users should have some visual feedback about what element is currently focused, so that's been added. Additionally, in order for the outline to have the same border-radius, the interaction styles such as background and border styles have been moved onto the button element itself.
New outline when `:focus-visible` is applied
Previous styles are still preserved when hovering:
This also applies to the buttons in the sub-menu:
=> fix(dyte-controlbar-button): add focus outline and move interaction styles onto button

packages/angular-library/projects/components/src/lib/stencil-generated/components.ts, packages/core/src/components.d.ts, packages/core/src/components/dyte-emoji-picker/dyte-emoji-picker.css, packages/core/src/components/dyte-emoji-picker/dyte-emoji-picker.tsx, packages/core/src/utils/assets.ts, packages/vue-library/lib/components.ts
- added focusWhenOpened prop to control this behavior, defaults to true
- Fixed flex layout issue that would only appear when search results showed a small enough (less than a full page) matches for the query.
- Fixed an issue where if search input was populated before emojis load the search query would be erased
- Keeps emoji json data in memory so it is only fetched once. Also, it looks like the cdn is setting `cache-control: no-cache` in the response!
Before:
After:
=> feat(dyte-emoji-picker): optionally focus emoji picker search when opened

packages/core/src/components/dyte-sidebar/dyte-sidebar.tsx
Renders dyte-participants and dyte-chat component using `<Render/>` to work with older add-ons
=> fix: render participants and chat components using Render

packages/core/src/components/dyte-meeting/dyte-meeting.tsx, packages/core/src/components/dyte-ui-provider/dyte-ui-provider.tsx
Users were not able to switch to Breakout rooms due to an internal error in UI Kit (updateStates is not a function). It used to work on a retry because the listener is attached on the meeting using once so it doesn't interfere the next time.
Same was happening for cases such as Join another breakout room, Move to main room.
Fixed `this` binding to ensure correct updateStates function gets picked.
=> fix(breakout-rooms): breakout rooms were not starting the first time

CHANGELOG.md, package-lock.json, packages/angular-library/projects/components/package.json, packages/core/package.json, packages/core/src/components/dyte-meeting/dyte-meeting.tsx, packages/core/src/components/dyte-ui-provider/dyte-ui-provider.tsx, packages/react-library/package.json, packages/vue-library/package.json
Users were not able to switch to Breakout rooms due to an internal error in UI Kit (updateStates is not a function). It used to work on a retry because the listener is attached on the meeting using once so it doesn't interfere the next time.
Same was happening for cases such as Join another breakout room, Move to main room.
Fixed this binding to ensure correct updateStates function gets picked.
=> chore(release): breakout room joining & creation fixes
